# Generated by Django 4.0.1 on 2022-01-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username2', models.CharField(max_length=30)),
                ('firstn', models.CharField(max_length=10)),
                ('secondn', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
